export const apiUrl = {
  login: `/login`,
  assetsCategory: '/assets/category',
  assetsModel: '/assets/model',
  assets: '/assets',
  assetInfo: '/assets/Details',
  assetInfoEdit: '/assets/DetailsEdit',
  assetImage: '/assets/Image',
  assetQRCode: '/assets/QRCode',
  assetLicenses: '/assets/Licenses',
  assetComponents: '/assets/Components',
  assetHistory: '/assets/History',
  assetMaintenances: '/asset/Maintenances',
  assetFiles: '/asset/Files',
  licenses: '/licenses',
  licensesCategory: '/licenses/category',
  licensesManufacturers: '/licenses/manufacturers',
  licenseInfoEdit: '/licenses/DetailsEdit',
  components: '/components',
  component: '/components/:id',
  licenseInfo: '/licenses/Details',
  licenseDeploys: '/licenses/Deployes',
  licenseHistory: '/licenses/History',
  addAssetManufacturer: '/asset_manufacturer',
};

export const routePath = {
  main: '/',
  login: '/login',
  dashboard: '/dashboard',
  accessories: '/accessories',
  assets: '/Assets',
  addAsset: 'AddAsset',
  editAsset: 'EditAsset/:id',
  assetDetails: 'AssetDetails/:id',
  pageNotFound: '/PageNotFound',
  licenses: 'Licenses',
  addLicense: 'AddLicense',
  editLicense: 'EditLicense/:id',
  components: '/Components',
  licenseDetails: 'LicenseDetails/:id',
  addManufacturer: '/Manufacturer/Add',
};
