export const AssetInfoData = {
  keys: [
    'IdMock',
    'NameMock',
    'SerialMock',
    'ModelMock',
    'ManufacturerMock',
    'CategoryMock',
    'StatusMock',
    'AssetTagMock',
    'NotesMock',
    'WarantyMock',
    'Order numberMock',
    'Date of purchaseMock',
    'Purchase costMock',
    'Created atMock',
    'CheckoutsMock',
    'CheckinsMock',
    'RequestsMock',
  ],
  values: [
    123,
    'AssetNameMock',
    'YYEz64GgdQ3MMock',
    'ModelMock',
    'ManufacturerMock',
    'categoryMock',
    'Ready to deployMock',
    'assetTagMock',
    'some notesMock',
    6,
    '123',
    '22/02/2022',
    200,
    '22/02/2022',
    2,
    2,
    1,
  ],
};
