name: CI

on:
  pull_request:
    branches: ['develop']
  push:
    branches: ['develop', 'feature/*']

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          allowed_prefixes: 'feature/INZ-'
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      include: './../templates/ci-template.yaml'
